package cerberus

import "testing"

// TestConformanceVectors runs every vector against the reference scanner.
//
// 🔑 THE EXPECTATIONS WERE COMPUTED BY HAND FROM THE SPECIFICATION, NOT CAPTURED FROM THIS
// IMPLEMENTATION. That distinction is the whole value of the file: a vector generated by running
// the code it is meant to check agrees with whatever the code does, including whatever the code
// gets wrong. Every value here — 0.7222 and 0.5 for the dedup pair, 2 and 4 for the timezone pair,
// the membership lists at both window edges — is derivable from the prose in scanspec.go with a
// calculator.
func TestConformanceVectors(t *testing.T) {
	vectors, err := Vectors()
	if err != nil {
		t.Fatalf("load vectors: %v", err)
	}
	if len(vectors) < 11 {
		t.Fatalf("%d vectors; the suite must cover the window boundary at BOTH ends, the dedup "+
			"unit on a multi-event session, the arrival-stream union, tz-unresolvable drops, the "+
			"empty scan, and verdict_filter in both positions", len(vectors))
	}
	for _, v := range vectors {
		t.Run(v.Name, func(t *testing.T) {
			s := NewMemoryScanner(v.Observations, v.Now)
			for _, err := range CheckVector(s, v) {
				t.Error(err)
			}
		})
	}
}

// TestDedupUnitVectorsActuallyDisagree is the guard on the guard.
//
// The dedup unit is load-bearing rather than incidental, and the two vectors that cover it are
// identical in every respect but one. If they ever came to produce the same answer — because
// somebody simplified the fixture, or because the aggregate stopped depending on row count — the
// pair would still PASS while covering nothing. An adopter who scanned events where the rule means
// session births would get the shipped bug back and no conformance run would see it.
func TestDedupUnitVectorsActuallyDisagree(t *testing.T) {
	vectors, err := Vectors()
	if err != nil {
		t.Fatal(err)
	}
	// * Select on the DEVICE-COHORT grouping, which only the dedup pair uses. Selecting on
	// * "unit=event and aggregate=hhi" alone matched three other vectors, and the last one to match
	// * won — so an earlier draft of this test compared the arrival-stream vector against the dedup
	// * one, reported "these do not share a substrate", and was right for entirely the wrong reason.
	var byEvent, bySession *Vector
	for i := range vectors {
		if len(vectors[i].Spec.GroupBy) != 1 || vectors[i].Spec.GroupBy[0] != GroupDeviceCohort {
			continue
		}
		switch vectors[i].Spec.Unit {
		case UnitEvent:
			byEvent = &vectors[i]
		case UnitSessionFirstEvent:
			bySession = &vectors[i]
		}
	}
	if byEvent == nil || bySession == nil {
		t.Fatal("the dedup-unit pair is missing; it is the vector this module exists for")
	}
	if len(byEvent.Observations) != len(bySession.Observations) {
		t.Fatal("the dedup pair does not share a substrate, so the difference between them is not " +
			"the unit and they measure nothing about it")
	}
	a, b := byEvent.Expect.Groups[0], bySession.Expect.Groups[0]
	if a.Units == b.Units {
		t.Errorf("both units yield %d rows — the fixture has no multi-event session, so an adapter "+
			"that ignores the unit passes both vectors", a.Units)
	}
	if a.Value != nil && b.Value != nil && nearly(*a.Value, *b.Value) {
		t.Errorf("both units yield the same statistic (%g) — the pair straddles nothing", *a.Value)
	}
}
